### PR TITLE
Option to update parent when sub budgets amount exceeds parent

### PR DESCRIPTION
**Pull request by BenjaminGroseclose**

### CODE REVIEW

**Comment by BenjaminGroseclose** [comment]
Good point, ill update that now as well.

**Comment by BenjaminGroseclose** [comment]
@ianmann56  I think it is updated

**Comment by ianmann56** [comment]
Sorry, I totally reviewed this last monday but forgot to submit the review. haha

**Comment by ianmann56** [comment]
I think I'm gonna take this one over cause it's a key feature in my eyes

**Comment by BenjaminGroseclose** [comment]
Sounds good :)

**Comment by BenjaminGroseclose** [comment]
Sorry been a bit out of this PR, what do you want me to take.

**Pull request closed without merging**
